//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbKnowEntities : DbContext
    {
        public dbKnowEntities()
            : base("name=dbKnowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Escola> Escola { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Serie> Serie { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
    }
}
