//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.Disciplina = new HashSet<Disciplina>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public bool Admin { get; set; }
        public string Cpf { get; set; }
        public long IdSexo { get; set; }
        public long IdFoto { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Foto Foto { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual ICollection<Disciplina> Disciplina { get; set; }
    }
}
