//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public long Id { get; set; }
        public string Cep { get; set; }
        public string Endereco1 { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public long IdBairro { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Bairro Bairro { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
