//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escola
    {
        public Escola()
        {
            this.Alunoes = new HashSet<Aluno>();
        }
    
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<long> IdProfessorAdmin { get; set; }
        public long IdPlano { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Aluno> Alunoes { get; set; }
        public virtual Plano Plano { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
