//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public Foto()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public long Id { get; set; }
        public string UrlFoto { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
