//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.PerfilAcessoes = new HashSet<PerfilAcesso>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public Nullable<long> IdMenuPai { get; set; }
        public string Url { get; set; }
        public string Imagem { get; set; }
        public long IdIdioma { get; set; }
        public Nullable<long> Ordem { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual ICollection<PerfilAcesso> PerfilAcessoes { get; set; }
    }
}
