//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sexo
    {
        public Sexo()
        {
            this.Alunoes = new HashSet<Aluno>();
            this.Professors = new HashSet<Professor>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Aluno> Alunoes { get; set; }
        public virtual ICollection<Professor> Professors { get; set; }
    }
}
